# Generated by Django 5.0.6 on 2026-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_part_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
