# Generated by Django 5.0.6 on 2026-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_backfill_product_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='torch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
