# Generated by Django 5.0.6 on 2026-07-29 19:04 — reordered by hand: tạo bảng
# PartBarcode + copy dữ liệu barcode cũ SANG bảng mới TRƯỚC KHI xoá field cũ,
# tránh mất mã đã gán trước đây (2026-07-28: field đơn cũ chỉ giữ được 1 mã/
# sản phẩm, đổi sang bảng riêng để 1 sản phẩm gắn được nhiều mã — Barcode + QR
# khác nội dung nhau trên cùng 1 hộp là chuyện thường gặp).

import django.db.models.deletion
from django.db import migrations, models


def copy_barcodes_forward(apps, schema_editor):
    Part = apps.get_model('catalog', 'Part')
    PartBarcode = apps.get_model('catalog', 'PartBarcode')
    for part in Part.objects.exclude(barcode='').only('tokin_part_no', 'barcode'):
        PartBarcode.objects.get_or_create(code=part.barcode, defaults={'part_id': part.pk})


def copy_barcodes_backward(apps, schema_editor):
    Part = apps.get_model('catalog', 'Part')
    PartBarcode = apps.get_model('catalog', 'PartBarcode')
    for pb in PartBarcode.objects.all():
        Part.objects.filter(pk=pb.part_id).update(barcode=pb.code)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_part_torch_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.part')),
            ],
            options={
                'db_table': 'catalog_part_barcode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(copy_barcodes_forward, copy_barcodes_backward),
        migrations.RemoveField(
            model_name='part',
            name='barcode',
        ),
    ]
