# Generated by Django 5.0.6 on 2026-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_part_barcode_partbarcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partbarcode',
            options={'ordering': ['part', '-created_at']},
        ),
        migrations.AddField(
            model_name='partbarcode',
            name='kind',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('barcode', 'Barcode')], max_length=10),
        ),
    ]
