# Generated by Django 5.0.6 on 2026-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_partbarcode_options_partbarcode_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partbarcode',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
