# Generated by Django 5.0.6 on 2026-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_partbarcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partbarcode',
            name='code',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
    ]
