# Generated by Django 5.0.6 on 2026-07-21 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_opportunity_lost_note_opportunity_lost_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketResolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_logs', to='crm.ticket')),
            ],
            options={
                'db_table': 'crm_ticket_resolution_log',
                'ordering': ['attempt_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticketresolutionlog',
            constraint=models.UniqueConstraint(fields=('ticket', 'attempt_no'), name='uniq_ticket_attempt_no'),
        ),
    ]
