# Generated by Django 5.0.6 on 2026-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_inboundorder_shortage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundline',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='outboundline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='purpose',
            field=models.CharField(choices=[('sale', 'Hàng bán'), ('project', 'Hàng xuất dự án')], db_index=True, default='sale', max_length=10),
        ),
    ]
