# Generated by Django 5.0.6 on 2026-07-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_outboundline_line_total_outboundline_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='delivered_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='flow_type',
            field=models.CharField(choices=[('internal', 'Nội bộ'), ('supplier', 'Nhà cung cấp')], db_index=True, default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbounds_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
