# Generated by Django 5.0.6 on 2026-07-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_inbound_line_tax_pct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['bin__full_code', 'id']},
        ),
    ]
