# Generated by Django 5.0.6 on 2026-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_inventoryitem_ordering_tiebreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
