# Generated by Django 5.0.6 on 2026-07-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_inbound_outbound_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecount',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
