# Generated by Django 5.0.6 on 2026-07-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0014_cyclecount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
