# Generated by Django 5.0.6 on 2026-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_inboundorder_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='manual_po_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
