# Generated by Django 5.0.6 on 2026-07-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_inboundorder_manual_po_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundline',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='delivered_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbounds_shipped', to=settings.AUTH_USER_MODEL),
        ),
    ]
