# Generated by Django 5.0.6 on 2026-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0017_outboundline_tax_pct_outboundorder_delivered_by_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
