# Generated by Django 5.0.6 on 2026-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_partbarcode_code'),
        ('wms', '0018_alter_bin_bin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_no',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('part', 'lot_no'), name='lot_unique_per_part'),
        ),
    ]
