# Generated by Django 5.0.6 on 2026-08-19 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_partbarcode_code'),
        ('crm', '0020_ticketresolutionlog_and_more'),
        ('wms', '0019_alter_lot_lot_no_lot_lot_unique_per_part'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='torch',
            field=models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.torch'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='part',
            field=models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.part'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='part',
            field=models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.part'),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='torch',
            field=models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.torch'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('torch', 'lot_no'), name='lot_unique_per_torch'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', False), ('torch__isnull', True)), models.Q(('part__isnull', True), ('torch__isnull', False)), _connector='OR'), name='lot_part_xor_torch'),
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', False), ('torch__isnull', True)), models.Q(('part__isnull', True), ('torch__isnull', False)), _connector='OR'), name='serial_part_xor_torch'),
        ),
    ]
