# Generated by Django 5.0.6 on 2026-07-21 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'accounts_capability',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Khách hàng'), ('sales', 'Sales'), ('warehouse', 'Nhân viên kho'), ('wh_manager', 'Quản lý kho'), ('service', 'Kỹ sư dịch vụ'), ('manager', 'Quản lý'), ('ceo', 'CEO'), ('admin', 'Admin')], max_length=20)),
                ('is_granted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.capability')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_role_capability_grant',
            },
        ),
        migrations.AddConstraint(
            model_name='rolecapabilitygrant',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='uniq_role_capability'),
        ),
    ]
