# Generated by Django 5.0.6 on 2026-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
