# Generated by Django 5.0.6 on 2026-07-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_opportunity_lost_note_opportunity_lost_reason'),
        ('sales', '0006_salesorder_payment_terms_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.contract'),
        ),
    ]
